---
title: Event Processing
author: andrea perlato
date: '2019-01-23'
slug: event-processing
categories:
  - theory
tags:
  - event processing
---

<style>
body {
text-align: justify}
</style>

**Process Data** </br>
Event data consists of three basic components: the why, the what and the who. </br>
Analysing event data is an iteractive process of three steps: extraction (from raw data to event log), processing (removing redundant details, enrich data by calculating variables) and analysis. </br>
The analysis could be for instance which are the roles of different doctors and nurses **organization** and how they work together. There is also in the analysis the **controll-flow prospective** (e.g. what is the journey of a patient throughthe emergency rooms). Finally, the performance prospective, focus on the time and **efficiency** (e.g. how long does it take before a patient can leave the emergency rooms). </br>

**A first glimpse of the event log**
Some initial question about event log are: </br>
How many **cases** are described? </br>
How many distinct **activities** are performed? </br>
How many **events** are recorded? </br>
What is the **time period** in which the data is recorded? </br>

To analys the process data, we use the [**bupaR package**](https://www.bupar.net/index.html).















