---
title: How to create 3D and 4D plot
author: andrea perlato
date: '2019-06-07'
slug: how-to-create-3d-and-4d-plot
categories:
  - graph
tags:
  - 3D
  - 4D
---

<style>
body {
text-align: justify}
</style>

A 3D plot is quite popular, in particular in business presentation, but it is almost always inappropriately used. In fact, it is rare to see a 3D plot that could not be improved by turning into a regular 2D figure. </br>
Visualizations using 3D position scales can sometimes be appropriate, however. If the visualization is show it slowly rotation, rather than a static image from one prospective, will allow the viewer to discern where in 3D space different graphicla elements resides. The human brain is very good at reconstructing a 3D scene from a series of images taken from different angles, and the slow rotation of the graphic provides exactly these images. </br>
We’ll use the [**iris data set**](https://en.wikipedia.org/wiki/Iris_flower_data_set) in the following examples.

```{r, echo=TRUE, comment=NA, message=FALSE, warning=FALSE, fig.align='center', out.width = '100%'}
# Load data
data(iris)
head(iris)

# Load libraries
library(plot3D)

# Define coordinates
x <- sep.l <- iris$Sepal.Length
y <- pet.l <- iris$Petal.Length
z <- sep.w <- iris$Sepal.Width

# Add small dots on basal plane and on the depth plane
scatter3D_fancy <- function(x, y, z,..., colvar = z)
  {
   panelfirst <- function(pmat) {
      XY <- trans3D(x, y, z = rep(min(z), length(z)), pmat = pmat)
      scatter2D(XY$x, XY$y, colvar = colvar, pch = ".", 
              cex = 2, add = TRUE, colkey = FALSE)
   
      XY <- trans3D(x = rep(min(x), length(x)), y, z, pmat = pmat)
      scatter2D(XY$x, XY$y, colvar = colvar, pch = ".", 
              cex = 2, add = TRUE, colkey = FALSE)
  }
  scatter3D(x, y, z, ..., colvar = colvar, panel.first=panelfirst,
    colkey = list(length = 0.5, width = 0.5, cex.clab = 0.75)) 
}

# Define like color
scatter3D_fancy(x, y, z, pch = 16,
    ticktype = "detailed", theta = 15, d = 2,
    main = "Iris data",  clab = c("Petal", "Width (cm)") )

```

In order to generate a fancy scatter plot with small dots on balsal palne the scater3D_fancu was created.  
Now, in order to create 3D histogram we will use the [**VADeaths data set**](https://app.quadstat.net/dataset/r-dataset-package-datasets-vadeaths). 
The death rates are measured per 1000 population per year. They are cross-classified by age group (rows) and population group (columns).









