---
title: Time Series Classification
author: andrea perlato
date: '2019-04-05'
slug: time-series-classification
categories:
  - machine learning
  - time series
tags:
  - time series classification
  - time series analysis
---

<style>
body {
text-align: justify}
</style>


In order to perform a **Time series Classification** we use **Decision Tree**, and then we look at the performance of the classification. </br>

We use the [**Synthetic Control Chart Time Series**](http://kdd.ics.uci.edu/databases/synthetic_control/synthetic_control.html). This dataset contains 600 examples of control charts synthetically generated by the process in Alcock and Manolopoulos (1999). 

```{r, echo=TRUE, comment=NA, message=FALSE, warning=FALSE, fig.align='center', out.width = '100%'}
data <- read.table("C:/07 - R Website/dataset/TS/synthetic_control.txt", header = FALSE)

# Data Preparation
pattern100 <- c(rep('Normal', 100),
             rep('Cyclic', 100),
             rep('Increasing trend', 100),
             rep('Decreasing trend', 100),
             rep('Upward shift', 100),
             rep('Downward shift', 100))

# Create data frame
newdata <- data.frame(data, pattern100)

# Classification with Decision Tree
library(party)
tree <- ctree(pattern100~., newdata)

# Classification Performance
tab <- table(Predicted = predict(tree, newdata), Actual = newdata$pattern100) # confusion matrix
tab
sum(diag(tab))/sum(tab) # accuracy

```
From the resul of the tree model (not shown here) we have 25 terminal nodes, and 49 branches.
From the **Confusin Matrix** above, we can see that we have si different patterns, and in the main diagonal we have the corrected prediction, and the off main diagonalvalues say to use the numebr of missclassified observations. The **Accuracy** is **95.16%**. </br>
The worst misclassification is for **Decreasing trend** with **8** misclassified observations. Moreover, the maximum confusion is for **Downward shift**. 
On the contrary, **Normal trend** is 100% correctly classified.









