---
title: Cox Proportional Hazards Model
author: andrea perlato
date: '2019-05-13'
slug: cox-proportional-hazards-model
categories:
  - survival analysis
tags:
  - cox proportional hazards
---

<style>
body {
text-align: justify}
</style>

An hazard rate is the probability estimate of the time it takes for an event to take place. The event can be anything ranging from death of an organism or failure of a machine or any other time to event setting. </br>
There are external factors that influence the probabililty of an event, **covariates**. For example: how many miles was the car used or did the owner exchange the oil regularly. The proportional hazards model allows us to incorporate thse covariance into our model, and it makes th probability estimate much more accurate.
In **Medical Setting** covariance cold be for example: gender, age, weight, occupation, treatment, other diseases. In **Engineering Setting** covariance coul be age, material, construction, environment, frequency of usage. </br>

The assumption of the [**Cox Proportional Hazards Model**](https://en.wikipedia.org/wiki/Proportional_hazards_model) is possible to estimate the effect of the beta parameters without any consideration of the hazard function. In fact, [**David Cox**](https://en.wikipedia.org/wiki/David_Cox_(statistician)) observed that if the proportional hazards assumption holds, then it is possible to estimate the beta effect parameters without any consideration of the hazard function.