---
title: Survival Trees
author: andrea perlato
date: '2019-05-13'
slug: survival-trees
categories:
  - survival analysis
tags:
  - survival trees
---

<style>
body {
text-align: justify}
</style>

A survival tree is a decision tree fitted on the survival data. It allows covariates to be incorporated quite like in a Cox Proportional Hazard. </br>
When we use a survival treee, we have to keep a few things in mind. First of all, it is a very good choice for huge dataset. Decision or survival trees require a huge amount of data to get precise enough. Survival trees are non-linear models.

**Prostate Cancer Dataset** </br>
We will use as a template for survival analysis the prostate cancer dataset. The dataset come from a study on prosthetic cancer patients, and it contains several variables to indicate or are in correlation with prosthetic cancer. The data contain 63 patients and 8 independent variables. The main goal is to compare two different treatments identified with 1 or 2. Both ot these are surgical treatments which are pretty much indicative in higher stages of prostate cancer.
The two tretments 1 and 2 differ in the amount of removed tissue and the type of tisue it was primarily removed. </br>
The time in the dataset was measured in months. The variable **status** can be 0=censoring (loss of follow up or quitting the study), or 1=no censoring.
The variable **sh** is the blod measurement hormone. The variable **size** is the tumor size at the beginning of the study. The variable **index** is the **Gleason Scoring System**, because tumor has different stages and they actually start to metastasize other boby parts at higher index of **Gleason Scoring System**.

```{r, echo=TRUE, comment=NA, message=FALSE, warning=FALSE, fig.align='center', out.width = '100%'}
prost <- read.table("C:/07 - R Website/dataset/TS/prostate-cancer.txt", header = FALSE)

colnames(prost) = c("patient", "treatment", "time", "status", "age", "sh", "size", "index")
head(prost)

# Survial Trees
library(survival)
library(ranger)
streefit <- ranger(Surv(time, status) ~ treatment + age + sh + size + index, data=prost,
                   importance = "permutation", # permutation is a solid choice in survival trees
                   splitrule = "extratrees", # used for survival logrank
                   seed = 43)

# Average the survival models
death_times <- streefit$unique.death.times 
surv_prob <- data.frame(streefit$survival) # survival probability oer each tree
avg_prob <- sapply(surv_prob, mean) # mean proability of all trees

# Plot the survival tree model averaged
plot(death_times, avg_prob,
     type = "s", # step plot
     ylim = c(0,1),
     col = "red", lwd = 2, bty = "n",
     ylab = "Survival Probability",
     xlab = "Time in Months",
     main = "Survival Tree Model\nAverage Survival Curve")


```

To visualize the survival tree there are severl way to do that. We can fro example plot the survival function for each study participant but that us usually not giving out any extra information. Therefore, the best and easiest way is to plot the averaged survival functiona s shown above.









